add_subdirectory(angelwrap)

add_subdirectory(cin)
add_subdirectory(ftlib)
add_subdirectory(ref_gl)
add_subdirectory(snd_openal)

add_subdirectory(irc)

add_subdirectory(game)
add_subdirectory(cgame)

add_subdirectory(client)
add_subdirectory(server)
# add_subdirectory(tv_server)

add_subdirectory(ui)
